[package]
authors = ["Christian Kauhaus <christian@kauhaus.de>"]
edition = "2018"
name = "esera-mqtt"
version = "0.2.0"

[dependencies]
anyhow = "1"
chrono = "0.4.19"
dotenv = "0.15.0"
env_logger = "0.7.1"
lazy_static = "1.4.0"
log = "0.4.11"
structopt = "0.3.17"
thiserror = "1.0.21"
nom = "6.0.0"
strum = "0.19.5"
strum_macros = "0.19.4"
bitflags = "1.2.1"
rumqttc = "0.2.0"
crossbeam = "0.8.0"
enum_dispatch = "0.3.4"

[dev-dependencies]
bstr = "0.2.14"
assert_matches = "1.4.0"
pretty_assertions = "0.6.1"
regex = "1.4.2"
rexpect = "0.4.0"
