[package]
authors = ["Christian Kauhaus <christian@kauhaus.de>"]
edition = "2018"
name = "esera-mqtt"
version = "0.1.0"

[dependencies]
anyhow = "1.0"
chrono = "0.4"
crossbeam = "0.7"
dotenv = "0.15"
env_logger = "0.7"
log = "0.4"
nom = "5.1"
rumqtt = "0.31"
smallstr = "0.1.0"
structopt = "0.3"
uuid = { version = "0.8", features = ["v4"] }
