[package]
authors = ["Christian Kauhaus <christian@kauhaus.de>"]
edition = "2018"
name = "esera-mqtt"
version = "0.2.0"

[dependencies]
anyhow = "1"
chrono = "0.4.15"
dotenv = "0.15.0"
env_logger = "0.7.1"
futures = "0.3"
lazy_static = "1.4.0"
log = "0.4.11"
regex = "1.4.1"
structopt = "0.3.17"
tokio-util = { version = "0.4", features = ["codec", "io"]}
tokio = { version = "0.3", features = ["full"] }
thiserror = "1.0.21"
nom = "5.1.2"

[dev-dependencies]
rexpect = "0.4.0"
